webTest/webTest/urls.py
from django.conf.urls import patterns, include, url
from web.views import *
#from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    url(r'^$',login),
    url(r'^login/', login),
    url(r'^person/$',person),
    url(r'^mission/$',mission),
    url(r'^report/$',daily_report),
    url(r'^load/$',load),
    (r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_URL}),
    #url(r'^admin/', include(admin.site.urls)),
)

webTest/web/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    person_id = models.IntegerField(max_length=9)
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    department = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    role = models.CharField(max_length=20)
    status = models.IntegerField(max_length=2)
    remark = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name;

class Mission(models.Model):
    mission_id = models.IntegerField(max_length=9)
    mission_name = models.CharField(max_length=100)
    accomplish = models.IntegerField(max_length=3)
    remark = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name;

class Submission(models.Model):
    submission_id = models.IntegerField(max_length=9)
    mission = models.ForeignKey(Mission)
    mission_order_id = models.IntegerField(max_length=9)
    status = models.IntegerField(max_length=2)
    content = models.CharField(max_length=200)
    remark = models.CharField(max_length=200)
    person = models.ManyToManyField(Person)

    def __unicode__(self):
        return self.name;

class Daily_report(models.Model):
    report_id = models.IntegerField(max_length=9)
    report_date = models.DateField()
    person = models.ForeignKey(Person)

    def __unicode__(self):
        return self.name;

class Report_describe(models.Model):
    describe_id = models.IntegerField(max_length=9)
    report = models.ForeignKey(Daily_report)
    report_order_id = models.IntegerField(max_length=9)
    mission = models.ForeignKey(Mission)
    submission = models.ForeignKey(Submission)
    content = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name;

class Code(models.Model):
    key = models.IntegerField(max_length=9)
    name = models.CharField(max_length=20)
    value = models.IntegerField(max_length=9)

    def __unicode__(self):
        return self.name;

webTest/web/forms.py
from django import forms

class NewPerson(forms.Form):
    name = forms.CharField(max_length=20)
    department = forms.CharField(max_length=50)
    title = forms.CharField(max_length=50)
    remark = forms.CharField(max_length=200)
    password = forms.CharField(max_length=10)
    #status = forms.ChoiceField(widget=forms.Select(),choices=Status,initial=Status[0])

class NewMission(forms.Form):
    name = forms.CharField(max_length=50)
    remark = forms.CharField(max_length=200)

class NewSubmission(forms.Form):
    mission_id = forms.IntegerField(max_value=9)
    content = forms.CharField(max_length=200)
    remark = forms.CharField(max_length=200)

webTest/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>Task Management</title>
	<link rel="stylesheet" href="/static/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="/static/jquery-ui.min.css" type="text/css" media="all" />
    <script type="text/javascript" src="/static/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/static/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/web.js"></script>
</head>
<body>
<!-- Header -->
<div id="header">
	<div class="shell">
		<!-- Logo + Top Nav -->
		<div id="top">
			<h1><a href="/person/">Task Management</a></h1>
			<div id="top-navigation">
				Welcome <a href="/person/"><strong>
                {% block name %}
                {% endblock %}
				</strong></a>
				<span>|</span>
				<a href="/login/">Log out</a>
			</div>
		</div>
		<!-- End Logo + Top Nav -->

		<!-- Main Nav -->
		<div id="navigation">
			<ul>
			    {% block tab %}{% endblock %}
			</ul>
		</div>
		<!-- End Main Nav -->
	</div>
</div>
<!-- End Header -->
<!-- Container -->
<div id="container">
	<div class="shell">
		<div id="main">
            <div id="content">
            {% block content %}
            {% endblock %}
            </div>
		</div>
		<!-- Main -->
	</div>
</div>
<!-- End Container -->

<!-- Footer -->
<div id="footer">
	<div class="shell">
		<span class="left">&copy; 2014 - Gome</span>
		<span class="right">
			Copyright @yangchunxue email:springsnow.yang@gmail.com
        </span>
	</div>
</div>
<!-- End Footer -->

</body>
</html>

webTest/templates/daily_report.html
{% extends "base.html" %}

{% block name %}
    {{ loginName }}
{% endblock %}

{% block tab %}
    <li><a href="/person/"><span>Person</span></a></li>
	<li><a href="/mission/"><span>Mission</span></a></li>
    <li><a href="/report/" class="active"><span>Daily Report</span></a></li>
{% endblock %}

{% block content %}
    <!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Report Information</h2>
			<div class="right">
					<input type="submit" class="button" value="NewReport" onclick=show("report") />
				</div>
			</div>
		<!-- End Box Head -->

			<!-- Table -->
			<div class="table">
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<th>id</th>
                        <th>Date</th>
						<th>Person Name</th>
						<th>Report Order</th>
                        <th>Content</th>
                        <th>Mission</th>
                        <th>Mission Order</th>
					</tr>
                    {% for r in reportlist %}
                    <tr>
                        <td>{{ r.id }}</td>
                        <td>{{ r.date }}</td>
                        <td>{{ r.name }}</td>
                        <td>{{ r.order }}</td>
                        <td>{{ r.content }}</td>
                        <td>{{ r.missionName }}</td>
                        <td>{{ r.missionOrder }}</td>
                    </tr>
                    {% endfor %}
				</table>
	</div>
    <div id="report-hide" class="box" style="display: none">
				<!-- Box Head -->
				<div class="box-head">
					<h2>New Report</h2>
				</div>
					<!-- End Box Head -->
			<form action="" method="post">
			<!-- Form -->
				<div class="form">
                    <input id="ordern" type="text" name="ordern" style="display: none" />
                    <p><label>Date</label><input type="text" name="date" id="datepicker"></p>
                    <p>
                        <label>Person</label>
                        <select id="name_select" name="name" >
                            <option value={{ pid }}>{{ loginName }}</option>
                        </select>
                    </p>
                    <p>
                        <input type="button" onclick=newReport() value="new" />
                        <input type="button" onclick=deleteReport() value="delete" />
                    </p>
                    <div id="sub_report">
                        <!--<label>id:1</label>
                        <p><textarea></textarea></p>
                        <p>
                            <label>Link Submission</label>
                            <select>
                                <option></option>
                            </select>
                        </p>-->
                    </div>
			    </div>
				<!-- End Form -->
				<!-- Form Buttons -->
				<div class="buttons">
					<input type="button" class="button" value="cancel" onclick=hide("report") />
					<input type="submit" class="button" value="submit" />
				</div>
				<!-- End Form Buttons -->
			</form>
		</div>
{% endblock %}

webTest/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div>
    <p>{{ msg }}</p>
    <form action="" method="post">
        <p>
            <label>Login Name</label>
            <input type="text" name="name" />
        </p>
        <p>
            <label>Password</label>
            <input type="password" name="pwd" />
        </p>
        <input type="submit" class="button" value="submit" />
    </form>
</div>
{% endblock %}

webTest/templates/mission.html
{% extends "base.html" %}

{% block name %}
    {{ loginName }}
{% endblock %}

{% block tab %}
    <li><a href="/person/"><span>Person</span></a></li>
	<li><a href="/mission/" class="active"><span>Mission</span></a></li>
    <li><a href="/report/"><span>Daily Report</span></a></li>
{% endblock %}

{% block content %}
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Mission Information</h2>
			<div class="right">
                {% if role == 'admin' %}
				<label>New Mission</label>
					<input type="submit" class="button" value="new" onclick=show("mission") />
				{% endif %}
            </div>
		</div>
		<!-- End Box Head -->

			<!-- Table -->
			<div class="table">
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<th>id</th>
						<th>Name</th>
						<th>Mission Remark</th>
                        <th>SubMission Order</th>
                        <th>Status</th>
                        <th>Content</th>
                        <th>Remark</th>
                        <th>Link</th>
                        <th width="110" class="ac">Content Control</th>
                    </tr>
                    {% for m in missionlist %}
                    <tr>
                        <td>{{ m.id }}</td>
                        <td id="{{ m.id }}_name">{{ m.name }}</td>
                        <td id="{{ m.id }}_remark">{{ m.remark }}</td>
                        <td id="{{ m.id }}_order">{{ m.order }}</td>
                        <td id="{{ m.id }}_{{ m.order }}_status">{{ m.status }}</td>
                        <td id="{{ m.id }}_{{ m.order }}_content">{{ m.content }}</td>
                        <td id="{{ m.id }}_{{ m.order }}_subremark">{{ m.subremark }}</td>
                        <td>
                            <a class="link" href="/person/?mission={{ m.id }}&order={{ m.order }}">Person</a>
                            <a class="link" href="/report/?mission={{ m.id }}&order={{ m.order }}">Report</a>
                        </td>
                        <td>
                            <a id={{ m.id }} class="ico edit mission" onclick=editSub({{ m.id }},{{ m.order }}) >Edit</a>
                            {% if role == 'admin' %}
                            <a onclick=newSub({{ m.id }})>Add</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
				</table>
	</div>
	<!-- Table -->
    <!-- Box -->
			<div id="mission-hide" class="box" style="display: none">
				<!-- Box Head -->
				<div class="box-head">
					<h2>New Mission</h2>
				</div>
					<!-- End Box Head -->
			<form action="" method="post">
			<!-- Form -->
				<div class="form">
                    {{ form.as_p }}
			    </div>
				<!-- End Form -->
				<!-- Form Buttons -->
				<div class="buttons">
					<input type="button" class="button" value="cancel" onclick=hide("mission") />
					<input type="submit" class="button" value="submit" />
				</div>
				<!-- End Form Buttons -->
			</form>
		</div>
		<!-- End Box -->
    <!-- Box -->
			<div id="submission-hide" class="box" style="display: none">
				<!-- Box Head -->
				<div class="box-head">
					<h2>New Submission</h2>
				</div>
					<!-- End Box Head -->
			<form action="" method="post">
			<!-- Form -->
				<div class="form">
					{{ subform.as_p }}
                    <p>
                        <label>Link Person</label>
                        <select id="id_person" name="person">
                            {% for p in personList %}
                            <option value="{{ p.id }}">{{ p.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
			    </div>
				<!-- End Form -->
				<!-- Form Buttons -->
				<div class="buttons">
					<input type="button" class="button" onclick=hide("submission") value="cancel" />
					<input type="submit" class="button" value="submit" />
				</div>
				<!-- End Form Buttons -->
			</form>
		</div>
		<!-- End Box -->
    <div id="submission-update" class="box" style="display: none">
				<!-- Box Head -->
				<div class="box-head">
					<h2>Edit</h2>
				</div>
					<!-- End Box Head -->
			<form action="" method="post">
			<!-- Form -->
				<div class="form">
                    <p>
                        <label>MissionID</label>
                        <input id="id_mission_id" type="text" name="mission_id" />
                    </p>
                    <p>
                        <label>Name</label>
                        <input id="id_name" type="text" name="name" />
                    </p>
                    <p>
                        <label>Mission remark</label>
                        <input id="id_mremark" type="text" name="mremark" />
                    </p>
                    <p>
                        <label>Submission Order</label>
                        <input id="id_order" type="text" name="order" />
                    </p>
                    <p>
                        <label>Content</label>
                        <input id="id_content" type="text" name="content" />
                    </p>
                    <p>
                        <label>Status</label>
                        <select id="id_status" name="status">
                        {% for s in substatus %}
                            <option id="{{ s.id }}_option" value="{{ s.id }}">{{ s.status }}</option>
                        {% endfor %}
                        </select>
                    </p>
                    <p>
                        <label>Submission Remark</label>
                        <input id="id_sremark" type="text" name="sremark" />
                    </p>
                    <!--<p>
                        <label>Link Person</label>
                        <select id="id_linkperson" name="person">

                        </select>
                    </p>-->
			    </div>
				<!-- End Form -->
				<!-- Form Buttons -->
				<div class="buttons">
					<input type="button" class="button" value="cancel" onclick=Uhide("submission") />
					<input type="submit" class="button" value="submit" />
				</div>
				<!-- End Form Buttons -->
			</form>
		</div>
{% endblock %}

webTest/templates/person.html
{% extends "base.html" %}

{% block name %}
    {{ loginName }}
{% endblock %}

{% block tab %}
    <li><a href="/person/" class="active"><span>Person</span></a></li>
	<li><a href="/mission/"><span>Mission</span></a></li>
    <li><a href="/report/"><span>Daily Report</span></a></li>
{% endblock %}

{% block content %}
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Person Information</h2>
			<div class="right">
                {% if role == 'admin' %}
				<label>New Person</label>
					<input type="submit" class="button" value="new" onclick=show("person") />
                {% endif %}
				</div>
			</div>
		<!-- End Box Head -->

			<!-- Table -->
			<div class="table">
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<th>id</th>
						<th>Name</th>
						<th>Department</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Remark</th>
                        <th>Link</th>
					    <th width="110" class="ac">Content Control</th>
					</tr>
                    {% for p in personlist %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td id="{{ p.id }}_name">{{ p.name }}</td>
                        <td id="{{ p.id }}_department">{{ p.department }}</td>
                        <td id="{{ p.id }}_title">{{ p.title }}</td>
                        <td id="{{ p.id }}_position">{{ p.position }}</td>
                        <td id="{{ p.id }}_remark">{{ p.remark }}</td>
                        <td>
                            <a class="link" href="/mission/?person={{ p.id }}" >Mission</a>
                            <a class="link" href="/report/?person={{ p.id }}">Report</a>
                        <td>
                            <a id="person{{ p.id }}" onclick=editPerson({{ p.id }}) class="ico edit">Edit</a>
                        </td>
                    </tr>
                    {% endfor %}
						<!--<tr>
								<td><input type="checkbox" class="checkbox" /></td>
								<td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
								<td>12.05.09</td>
								<td><a href="#">Administrator</a></td>
								<td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
							</tr>
							-->
				</table>
                <!-- Pagging -->
				<!--<div class="pagging">
					<div class="left">Showing 1-12 of 44</div>
						<div class="right">
						    <a href="#">Previous</a>
							<a href="#">1</a>
							<a href="#">2</a>
							<a href="#">3</a>
							<a href="#">4</a>
							<a href="#">245</a>
							<span>...</span>
							<a href="#">Next</a>
							<a href="#">View all</a>
						</div>
					</div>
                </div>-->
				<!-- End Pagging -->
			</div>
			<!-- Table -->
    		<!-- Box -->
			<div id="person-hide" class="box" style="display: none">
				<!-- Box Head -->
				<div class="box-head">
					<h2>New</h2>
				</div>
					<!-- End Box Head -->
			<form action="" method="post">
			<!-- Form -->
				<div class="form">
                {{ form.as_p }}
			    </div>
				<!-- End Form -->
				<!-- Form Buttons -->
				<div class="buttons">
					<input type="button" class="button" value="cancel" onclick=hide("person") />
					<input type="submit" class="button" value="submit" />
				</div>
				<!-- End Form Buttons -->
			</form>
		</div>
		<!-- End Box -->
    <div id="person-update" class="box" style="display: none">
				<!-- Box Head -->
				<div class="box-head">
					<h2>Update</h2>
				</div>
					<!-- End Box Head -->
			<form action="" method="post">
			<!-- Form -->
				<div class="form">
                <p>
                    <input id="id_id" type="text" name="id" />
                </p>
                {{ form.as_p }}
                <select id="id_status" name="position">
                    {% for s in statuslist %}
                        <option id="{{ s.id }}_option" value="{{ s.id }}">{{ s.status }}</option>
                    {% endfor %}
                </select>
			    </div>
				<!-- End Form -->
				<!-- Form Buttons -->
				<div class="buttons">
					<input type="button" class="button" value="cancel" onclick=Uhide("person") />
					<input type="submit" class="button" value="submit" />
				</div>
				<!-- End Form Buttons -->
			</form>
		</div>
{% endblock %}